/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aproyectu4;

import static aproyectu4.UNKNOW.jTable1;
import static aproyectu4.UNKNOW.jTable2;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Mata
 */
public class BASE extends javax.swing.JFrame {
     Conexion cone=new Conexion();
Connection rege=cone.conexion();

    /**
     * Creates new form BASE
     */
    public BASE() {
        initComponents();
        verTablaAlumnos("");
        verTablaConferencistas("");
        total();
        this.setLocationRelativeTo(null);
        
        total();
    }
     void verTablaAlumnos(String clav){
        DefaultTableModel modeloDos=new DefaultTableModel();
        String sql="";
        modeloDos.addColumn("Clave");
        modeloDos.addColumn("Nombre");
        modeloDos.addColumn("Control");
        modeloDos.addColumn("Correo");
        modeloDos.addColumn("Conferencia");
        modeloDos.addColumn("Pago");
        
        tablaje.setModel(modeloDos);
        String [] dataje=new String[6];
        
        if (clav.equals("")) {
            sql="SELECT * FROM alumnos";
            
        }
        else{
            sql="SELECT* FROM alumnos WHERE CLAVE='"+clav+"'";

    }
        try {
              Statement sentencia= rege.createStatement();

           ResultSet rs=sentencia.executeQuery(sql);
            while (rs.next()) {  
                dataje[0]=rs.getString(1);
                dataje[1]=rs.getString(2);
                dataje[2]=rs.getString(3);
                dataje[3]=rs.getString(4);
                dataje[4]=rs.getString(5);
                dataje[5]=rs.getString(6);
                modeloDos.addRow(dataje);
            }
            
        } catch (Exception e) {
        }
        
     }
     
     
     
     
     
     
       void verTablaConferencistas(String nombre){
         

 String sql="";
        DefaultTableModel miModelo=new  DefaultTableModel();
        miModelo.addColumn("Clave");
        miModelo.addColumn("Conferencia");
        miModelo.addColumn("Asesor");
        miModelo.addColumn("Costo");
        miModelo.addColumn("Carga");
        tabla1.setModel(miModelo);
        String [] datos= new String[5];
       
        if (nombre.equals("")) {
             sql = "SELECT * FROM CONFERENCISTAS";
            
        }else {
             sql = "SELECT * FROM CONFERENCISTAS WHERE CLAVE ='"+nombre+"'";
            
        }
        
          
      
            
            
        
        try {
            
           Statement sentencia= rege.createStatement();

           ResultSet rs=sentencia.executeQuery(sql);
            while (rs.next()) {  
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                miModelo.addRow(datos);
             
                
                
            }
            tabla1.setModel(miModelo);
        } catch (SQLException ex) {
            Logger.getLogger(BASE.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        
    }
       public float total(){
           int contar=tablaje.getRowCount();
           float suma=0;
           for (int i = 0; i < contar; i++) {
               suma=suma+Float.parseFloat(tablaje.getValueAt(i,5).toString());
               
           }
           String cadena=Float.toString(suma);
           txtTotal.setText(cadena);
           return suma;
           
           
           
           
       }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaje = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        boton3 = new Swings.Boton();
        boton2 = new Swings.Boton();
        boton1 = new Swings.Boton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("BASE DE DATOS ALUMNOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tablaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaje);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 570, 270));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabla1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 570, 270));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Ingresos Totales");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 140, 30));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 100, -1));

        boton3.setBackground(new java.awt.Color(255, 255, 204));
        boton3.setText("Regresar");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, -1, -1));

        boton2.setText("ELIMINAR ALUMNO");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        boton1.setText("ELIMINAR CONFERENCISTA");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/INVERTIR-EN-TECNOLOGIA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -70, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        Pincipal o=new Pincipal();
        o.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
  try {
            int file=tabla1.getSelectedRow();
            if (file<0) {
                JOptionPane.showMessageDialog(null, "Seleccione registro para eliminar");

            }
            String valor=tabla1.getValueAt(file,0).toString();
            if (file>=0) {
                int res;
                res=JOptionPane.showConfirmDialog(null, "¿Estas a punto de eliminar un conferencista ","CONFIRMAR",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                PreparedStatement rg=rege.prepareStatement("DELETE FROM  conferencistas WHERE clave ='"+valor+"'");
                rg.executeUpdate();
                JOptionPane.showMessageDialog(null,"Regitro borrado con exito");
                verTablaConferencistas("");
            }
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        try {
            int file=tablaje.getSelectedRow();
            if (file<0) {
                JOptionPane.showMessageDialog(null, "Seleccione registro para eliminar");

            }
            String valor=tablaje.getValueAt(file,0).toString();
            if (file>=0) {
                int res;
                res=JOptionPane.showConfirmDialog(null, "¿Estas a punto de eliminar a un alumno ","CONFIRMAR",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                PreparedStatement rg=rege.prepareStatement("DELETE FROM  alumnos WHERE clave ='"+valor+"'");
                rg.executeUpdate();
                JOptionPane.showMessageDialog(null,"Regitro borrado con exito");
                verTablaAlumnos("");
                total();
            }
        } catch (Exception e) {
        } // TODO add your handling code here:
    }//GEN-LAST:event_boton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BASE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swings.Boton boton1;
    private Swings.Boton boton2;
    private Swings.Boton boton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable tabla1;
    public static javax.swing.JTable tablaje;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
